### ISSUE TITLE
[POST] Praticando com tidytuesday 1 - Dataset das Paraolimpíadas

### ISSUE THREAD

**Issue by IanniMuliterno** [R-Ladies-Sao-Paulo/blog#17]
## Tipo de contribuição

-   [ ] Melhoria em textos/arquivos já existentes
-   [x] Texto para o blog

## Descrição breve da contribuição

usando dados do tidytuesday para praticar programação em R, usando especialmente os pacotes tidyverse e ggplot2. O post também tem a intenção de incentivar e educar jovens e programadores iniciantes.

## Texto ou link para o texto

https://github.com/IanniMuliterno/Rladies_blog_1

## Declaro que....

-   [ X] Faço parte dos grupos que são público-alvo da R-Ladies São Paulo (mulheres cis, mulheres trans, homens trans, pessoas não-binárias e queer).

-   [ X] Aceito que o texto seja revisado e receba feedback antes de postar.

## OBS 

Fala pessoal, vi que não estou como colaborador, o invite que recebi em dezembro expirou antes que eu pudesse aceitar e só lembrei disso agora que precisei usar. Quando possível, me manda invite de novo, please?

**Comment by beatrizmilz** [comment]
Oi! Vi que o post já ficou pronto mas esqueci de fechar a issue. Muito obrigada pela sua colaboração <3
